json_get_path – JSON-Fortran
json_get_path Subroutine
181 statements
Source File
private subroutine json_get_path(json, p, path, found, use_alt_array_tokens, path_sep)
Returns the path to a JSON object that is part of a linked list structure.
The path returned would be suitable for input to json_get_by_path and related routines.
Note
If an error occurs (which in this case means a malformed JSON structure) then an exception will be thrown, unless found is present, which will be set to false. path will be a blank string.
Note
If json%path_mode/=1, then the use_alt_array_tokens and path_sep inputs are ignored if present.
Note
http://goessner.net/articles/JsonPath/ (path_mode=3) does not specify whether or not the keys should be escaped (this routine assumes not, as does http://jsonpath.com). Also, we are using Fortran-style 1-based array indices, not 0-based, to agree with the assumption in path_mode=1
Arguments
Type Intent Optional Attributes Name
class(json_core), intent(inout) :: json
type(json_value), intent(in), pointer :: p
a JSON linked list object
character(kind=CK,len=:), intent(out), allocatable :: path
path to the variable
logical(kind=LK), intent(out), optional :: found
true if there were no problems
logical(kind=LK), intent(in), optional :: use_alt_array_tokens
if true, then ‘()’ are used for array elements otherwise, ‘[]’ are used [default] (only used if path_mode=1)
character(kind=CK,len=1), intent(in), optional :: path_sep
character to use for path separator (otherwise use json%path_separator) (only used if path_mode=1)
Calls
Contents
Variables
array_end array_start consecutive_arrays element i istr n_children name parent_is_root parent_name parents_parent_var_type tmp use_brackets var_type
Subroutines
add_to_path
Variables
Type Visibility Attributes Name Initial
character(kind=CK,len=1), private :: array_end
for path_mode=1, the character to end arrays
character(kind=CK,len=1), private :: array_start
for path_mode=1, the character to start arrays
logical, private :: consecutive_arrays
check for array of array case
type(json_value), private, pointer :: element
for traversing the structure
integer(kind=IK), private :: i
counter
character(kind=CK,len=max_integer_str_len), private :: istr
for integer to string conversion (array indices)
integer(kind=IK), private :: n_children
number of children for parent
character(kind=CK,len=:), private, allocatable :: name
variable name
logical(kind=LK), private :: parent_is_root
if the parent is the root
character(kind=CK,len=:), private, allocatable :: parent_name
variable’s parent name
integer(kind=IK), private :: parents_parent_var_type
var_type for parent’s parent
type(json_value), private, pointer :: tmp
for traversing the structure
logical(kind=LK), private :: use_brackets
to use ‘[]’ characters for arrays
integer(kind=IK), private :: var_type
JSON variable type flag
Subroutines
subroutine add_to_path(str, path_sep)
prepend the string to the path
Arguments
Type Intent Optional Attributes Name
character(kind=CK,len=*), intent(in) :: str
string to prepend to path
character(kind=CK,len=1), intent(in), optional :: path_sep
path separator (default is ‘.’). (ignored if json%path_mode/=1)
Call graph
json_get_path calls encode_rfc6901, integer_to_string, add_to_path
encode_rfc6901 calls replace_string