json_value_print – JSON-Fortran
json_value_print Subroutine
241 statements
Source File
private recursive subroutine json_value_print(json, p, iunit, str, indent, need_comma, colon, is_array_element, is_compressed_vector, iloc)
Print the JSON structure to a string or a file.
Notes
This is an internal routine called by the various wrapper routines.
The reason the str argument is non-optional is because of a bug in v4.9 of the gfortran compiler.
Arguments
Type Intent Optional Attributes Name
class(json_core), intent(inout) :: json
type(json_value), intent(in), pointer :: p
integer(kind=IK), intent(in) :: iunit
file unit to write to (the file is assumed to be open)
character(kind=CK,len=:), intent(inout), allocatable :: str
if iunit==unit2str (-1) then the structure is printed to this string rather than a file. This mode is used by json_value_to_string.
integer(kind=IK), intent(in), optional :: indent
indention level
logical(kind=LK), intent(in), optional :: need_comma
if it needs a comma after it
logical(kind=LK), intent(in), optional :: colon
if the colon was just written
logical(kind=LK), intent(in), optional :: is_array_element
if this is an array element
logical(kind=LK), intent(in), optional :: is_compressed_vector
if True, this is an element from an array being printed on one line [default is False]
integer(kind=IK), intent(inout) :: iloc
current index in str. should be set to 0 initially. [only used when str is used.]
Calls
Contents
Variables
count element i is_array is_vector print_comma s s_indent spaces str_escaped tab tmp write_file write_string
Subroutines
write_it
Variables
Type Visibility Attributes Name Initial
integer(kind=IK), private :: count
number of children
type(json_value), private, pointer :: element
for getting children
integer(kind=IK), private :: i
counter
logical(kind=LK), private :: is_array
if this is an element in an array
logical(kind=LK), private :: is_vector
if all elements of a vector are scalars of the same type
logical(kind=LK), private :: print_comma
if the comma will be printed after the value
character(kind=CK,len=:), private, allocatable :: s
the string appended to str
character(kind=CK,len=:), private, allocatable :: s_indent
the string of spaces for indenting (see tab and spaces)
integer(kind=IK), private :: spaces
number of spaces for indenting
character(kind=CK,len=:), private, allocatable :: str_escaped
escaped version of name or str_value
integer(kind=IK), private :: tab
number of tabs for indenting
character(kind=CK,len=max_numeric_str_len), private :: tmp
for value to string conversions
logical(kind=LK), private :: write_file
if we are writing to a file
logical(kind=LK), private :: write_string
if we are writing to a string
Subroutines
subroutine write_it(advance, comma, space_after_comma)
write the string s to the file (or the output string)
Arguments
Type Intent Optional Attributes Name
logical(kind=LK), intent(in), optional :: advance
to add line break or not
logical(kind=LK), intent(in), optional :: comma
print comma after the string
logical(kind=LK), intent(in), optional :: space_after_comma
print a space after the comma
Call graph
json_value_print calls integer_to_string, escape_string, real_to_string, write_it
escape_string calls valid_json_hex
real_to_string calls compact_real_string