to_unicode – JSON-Fortran
to_unicode Interface
3 statements
Source File
public interface to_unicode
Convert a ‘DEFAULT’ kind character input to ‘ISO_10646’ kind and return it
Calls
Called by
Contents
Module Procedures
to_uni to_uni_vec
Module Procedures
private pure function to_uni(str)
Author
Izaak Beekman
Convert string to unicode (CDK to CK).
Arguments
Type Intent Optional Attributes Name
character(kind=CDK,len=*), intent(in) :: str
Return Value character(kind=CK,len=len(str))
private pure function to_uni_vec(str)
Author
Izaak Beekman
Convert array of strings to unicode (CDK to CK).
Read more…
Arguments
Type Intent Optional Attributes Name
character(kind=CDK,len=*), intent(in), dimension(:) :: str
Return Value character(kind=CK,len=len(str)), dimension(size(str))
Call graph
to_unicode calls to_uni_vec, to_uni
wrap_json_add_logical_vec_by_path calls to_unicode
wrap_json_add_string_vec_by_path calls to_unicode
json_update_string_name_ascii calls to_unicode
wrap_json_file_get_integer calls to_unicode
wrap_json_file_add_object calls to_unicode
wrap_json_file_add_real32 calls to_unicode
wrap_assign_string_to_json_file calls to_unicode
default_join_ucs4 calls to_unicode
json_file_rename_path_ascii calls to_unicode
wrap_json_get_alloc_string_vec_by_path calls to_unicode
wrap_json_file_load_from_string calls to_unicode
json_rename_by_path_name_ascii calls to_unicode
wrap_json_value_add_logical calls to_unicode
wrap_json_file_add_integer_vec calls to_unicode
json_file_add_string_vec_path_ascii calls to_unicode
wrap_json_value_add_real_vec calls to_unicode
wrap_json_get_integer_vec_by_path calls to_unicode
json_file_rename_name_ascii calls to_unicode
wrap_json_add_integer_by_path calls to_unicode
wrap_json_value_add_string_vec calls to_unicode
wrap_json_value_create_null calls to_unicode
wrap_json_get_array_by_path calls to_unicode
wrap_json_update_logical calls to_unicode
json_add_string_by_path_value_ascii calls to_unicode
wrap_json_update_real32 calls to_unicode
json_file_update_string_val_ascii calls to_unicode
wrap_json_file_variable_matrix_info calls to_unicode
json_file_add_string_path_ascii calls to_unicode
wrap_json_file_get_string_vec calls to_unicode
ucs4_neq_default calls to_unicode
wrap_json_value_add_real calls to_unicode
wrap_json_info_by_path calls to_unicode
wrap_json_file_variable_info calls to_unicode
wrap_json_file_get_real calls to_unicode
wrap_json_add_member_by_path calls to_unicode
wrap_json_file_add_string calls to_unicode
wrap_json_add_real32_vec_by_path calls to_unicode
wrap_json_value_add_integer_vec calls to_unicode
wrap_json_file_get_string calls to_unicode
wrap_json_file_valid_path calls to_unicode
wrap_json_add_logical_by_path calls to_unicode
wrap_json_get_real_by_path calls to_unicode
wrap_json_get_logical_by_path calls to_unicode
wrap_json_value_create_array calls to_unicode
wrap_json_file_get_real_vec calls to_unicode
wrap_json_value_add_integer calls to_unicode
wrap_json_file_add_real_vec calls to_unicode
default_comp_ucs4 calls to_unicode
json_value_add_string_val_ascii calls to_unicode
wrap_json_value_create_object calls to_unicode
default_neq_ucs4 calls to_unicode
wrap_json_value_add_null calls to_unicode
wrap_json_value_add_real32_vec calls to_unicode
wrap_json_update_integer calls to_unicode
wrap_json_value_create_logical calls to_unicode
wrap_json_add_real32_by_path calls to_unicode
ucs4_comp_default calls to_unicode
json_rename_by_path_path_ascii calls to_unicode
wrap_json_file_remove calls to_unicode
wrap_json_matrix_info_by_path calls to_unicode
wrap_json_value_create_real32 calls to_unicode
json_add_string_vec_by_path_value_ascii calls to_unicode
wrap_json_get_path calls to_unicode
wrap_json_file_add_logical calls to_unicode
wrap_json_file_get_logical calls to_unicode
wrap_json_file_update_real calls to_unicode
wrap_json_update_real calls to_unicode
wrap_json_update_string calls to_unicode
wrap_json_file_add_logical_vec calls to_unicode
wrap_json_valid_path calls to_unicode
wrap_json_file_get_real32 calls to_unicode
wrap_json_get_real32_by_path calls to_unicode
wrap_json_file_valid_path_op calls to_unicode
wrap_json_add_real_vec_by_path calls to_unicode
json_update_string_val_ascii calls to_unicode
json_add_string_vec_by_path_path_ascii calls to_unicode
wrap_json_add_string_by_path calls to_unicode
wrap_json_file_get_real32_vec calls to_unicode
wrap_json_add_integer_vec_by_path calls to_unicode
wrap_json_file_add_real32_vec calls to_unicode
wrap_json_create_by_path calls to_unicode
json_value_add_string_name_ascii calls to_unicode
json_file_add_string_value_ascii calls to_unicode
wrap_json_value_remove_if_present calls to_unicode
json_value_add_string_vec_val_ascii calls to_unicode
wrap_json_add_real_by_path calls to_unicode
wrap_json_get_logical_vec_by_path calls to_unicode
wrap_json_file_get_object calls to_unicode
ucs4_join_default calls to_unicode
json_value_add_string_vec_name_ascii calls to_unicode
wrap_json_value_get_child_by_name calls to_unicode
wrap_json_get_string_by_path calls to_unicode
wrap_json_throw_exception calls to_unicode
wrap_json_value_create_string calls to_unicode
wrap_json_value_add_string calls to_unicode
wrap_json_value_add_real32 calls to_unicode
wrap_json_file_add_real calls to_unicode
wrap_json_file_update_integer calls to_unicode
wrap_json_file_get_alloc_string_vec calls to_unicode
wrap_json_file_add_integer calls to_unicode
wrap_json_get_real_vec_by_path calls to_unicode
wrap_json_value_create_real calls to_unicode
wrap_json_get_integer_by_path calls to_unicode
wrap_json_file_get_logical_vec calls to_unicode
wrap_json_value_rename calls to_unicode
wrap_initialize_json_file_from_string calls to_unicode
wrap_json_file_get_integer_vec calls to_unicode
wrap_json_parse_string calls to_unicode
wrap_json_get_by_path calls to_unicode
wrap_json_rename_by_path calls to_unicode
json_file_update_string_name_ascii calls to_unicode
wrap_json_get_string_vec_by_path calls to_unicode
wrap_initialize_json_file_from_string_v2 calls to_unicode
wrap_json_file_rename calls to_unicode
wrap_json_file_update_string calls to_unicode
wrap_json_file_update_real32 calls to_unicode
wrap_json_value_add_logical_vec calls to_unicode
wrap_json_value_create_integer calls to_unicode
wrap_json_file_update_logical calls to_unicode
json_file_add_string_vec_vec_ascii calls to_unicode
wrap_json_file_add_string_vec calls to_unicode
wrap_json_get_real32_vec_by_path calls to_unicode
json_add_string_by_path_path_ascii calls to_unicode
operator(SLASHSLASH) calls default_join_ucs4, ucs4_join_default
operator(SLASH=) calls ucs4_neq_default, default_neq_ucs4
json_file calls wrap_initialize_json_file_from_string, wrap_initialize_json_file_from_string_v2
operator(==) calls default_comp_ucs4, ucs4_comp_default